#!/usr/bin/env bash
# Servers are the piece of software generating and serving HTML pages
# Installing nginx on the web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Add rewrite rule to redirect /redirect_me to https://www.youtube.com/@cryptotechcoder
sed -i '/server_name _;/a location /redirect_me { return 301 }' /etc/nginx/sites-available/default

service nginx restart
